services:
  # Backend API Service
  - type: web
    name: yacht-jobs-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./yacht_jobs.db
      - key: REDIS_URL
        fromService:
          type: redis
          name: yacht-jobs-redis
          property: connectionString

      - key: CORS_ORIGINS
        value: https://yacht-jobs-frontend.onrender.com
    healthCheckPath: /health
    autoDeploy: false

  # Frontend Service
  - type: web
    name: yacht-jobs-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://yacht-jobs-backend.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: wss://yacht-jobs-backend.onrender.com
    healthCheckPath: /
    autoDeploy: false

  # Redis Service
  - type: redis
    name: yacht-jobs-redis
    maxmemoryPolicy: allkeys-lru
    plan: starter  # Free tier available 